os: linux
sudo: required
dist: xenial
language: python
cache: 
  - pip
python: '3.5'

before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements_test.txt

script:
 - pytest --cov-config=.coveragerc --cov=IntentionPrediction

after_success:
  - coveralls

notifications:
  email: false

