os: linux
sudo: required
dist: xenial
language: python
cache: 
  - pip
python: '3.5'


before_install: sudo apt-get update
install: 
  - sudo apt-get install build-essential
  - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev

before_script:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements_test.txt

script:
 - pytest --cov-config=.coveragerc --cov=IntentionPrediction

after_success:
  - coveralls

notifications:
  email: false

